[package]
name = "polsys"
version = "0.1.0"
edition = "2021"

[dependencies]
num = { "version" = "0.4" }

[build-dependencies]
cc = { "version" = "1.1" }

[package.metadata.typos.files]
extend-exclude = [
    "polsys-plp/README",
    "polsys-plp/lapack_plp.f",
    "polsys-plp/polsys_plp.f90",
]
