// GENERATED by generate_fixed_point.py
// DO NOT EDIT

// SPDX-FileCopyrightText: 2026 Alexandru Fikl <alexfikl@gmail.com>
// SPDX-License-Identifier: MIT

use num::complex::Complex64;

use polsys::{PolsysSolver, Polynomial, term};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let c = Complex64::new(0.0, 0.0);
    let mut poly = Polynomial::<2>::new(vec![
        vec![
            term([16, 0], 1.00000000000000),
            term([15, 1], 16.0000000000000),
            term([14, 2], 128.000000000000),
            term([14, 0], 16.0 * c),
            term([13, 3], 672.000000000000),
            term([13, 1], 224.0 * c),
            term([12, 4], 2580.00000000000),
            term([12, 2], 1576.0 * c),
            term([12, 0], 116.0 * c.powi(2) + 8.0 * c),
            term([11, 5], 7664.00000000000),
            term([11, 3], 7264.0 * c),
            term([11, 1], 1392.0 * c.powi(2) + 96.0 * c),
            term([10, 6], 18208.0000000000),
            term([10, 4], 24368.0 * c),
            term([10, 2], 8448.0 * c.powi(2) + 576.0 * c),
            term([10, 0], 496.0 * c.powi(3) + 96.0 * c.powi(2)),
            term([9, 7], 35296.0000000000),
            term([9, 5], 62752.0 * c),
            term([9, 3], 33440.0 * c.powi(2) + 2240.0 * c),
            term([9, 1], 4960.0 * c.powi(3) + 960.0 * c.powi(2)),
            term([8, 8], 56472.0000000000),
            term([8, 6], 127840.0 * c),
            term([8, 4], 95568.0 * c.powi(2) + 6268.0 * c),
            term([8, 2], 25312.0 * c.powi(3) + 4856.0 * c.powi(2)),
            term(
                [8, 0],
                1368.0 * c.powi(4) + 508.0 * c.powi(3) + 26.0 * c.powi(2) + 4.0 * c,
            ),
            term([7, 9], 74944.0000000000),
            term([7, 7], 209408.0 * c),
            term([7, 5], 206976.0 * c.powi(2) + 13280.0 * c),
            term([7, 3], 83456.0 * c.powi(3) + 15808.0 * c.powi(2)),
            term(
                [7, 1],
                10944.0 * c.powi(4) + 4064.0 * c.powi(3) + 208.0 * c.powi(2) + 32.0 * c,
            ),
            term([6, 10], 82432.0000000000),
            term([6, 8], 277696.0 * c),
            term([6, 6], 348416.0 * c.powi(2) + 21888.0 * c),
            term([6, 4], 195968.0 * c.powi(3) + 36576.0 * c.powi(2)),
            term(
                [6, 2],
                45312.0 * c.powi(4) + 16704.0 * c.powi(3) + 832.0 * c.powi(2) + 128.0 * c,
            ),
            term(
                [6, 0],
                2496.0 * c.powi(5) + 1504.0 * c.powi(4) + 208.0 * c.powi(3) + 32.0 * c.powi(2),
            ),
            term([5, 11], 74624.0000000000),
            term([5, 9], 297600.0 * c),
            term([5, 7], 460032.0 * c.powi(2) + 28352.0 * c),
            term([5, 5], 340736.0 * c.powi(3) + 62656.0 * c.powi(2)),
            term(
                [5, 3],
                118656.0 * c.powi(4) + 43328.0 * c.powi(3) + 2080.0 * c.powi(2) + 320.0 * c,
            ),
            term(
                [5, 1],
                14976.0 * c.powi(5) + 9024.0 * c.powi(4) + 1248.0 * c.powi(3) + 192.0 * c.powi(2),
            ),
            term([4, 12], 54792.0000000000),
            term([4, 10], 255024.0 * c),
            term([4, 8], 475128.0 * c.powi(2) + 28808.0 * c),
            term([4, 6], 446112.0 * c.powi(3) + 80928.0 * c.powi(2)),
            term(
                [4, 4],
                215928.0 * c.powi(4) + 78064.0 * c.powi(3) + 3604.0 * c.powi(2) + 552.0 * c,
            ),
            term(
                [4, 2],
                47664.0 * c.powi(5) + 28576.0 * c.powi(4) + 3880.0 * c.powi(3) + 592.0 * c.powi(2),
            ),
            term(
                [4, 0],
                2952.0 * c.powi(6)
                    + 2632.0 * c.powi(5)
                    + 692.0 * c.powi(4)
                    + 144.0 * c.powi(3)
                    + 16.0 * c.powi(2),
            ),
            term([3, 13], 31776.0000000000),
            term([3, 11], 170688.0 * c),
            term([3, 9], 376800.0 * c.powi(2) + 22560.0 * c),
            term([3, 7], 435840.0 * c.powi(3) + 78208.0 * c.powi(2)),
            term(
                [3, 5],
                276960.0 * c.powi(4) + 99264.0 * c.powi(3) + 4432.0 * c.powi(2) + 672.0 * c,
            ),
            term(
                [3, 3],
                90816.0 * c.powi(5) + 54144.0 * c.powi(4) + 7200.0 * c.powi(3) + 1088.0 * c.powi(2),
            ),
            term(
                [3, 1],
                11808.0 * c.powi(6)
                    + 10528.0 * c.powi(5)
                    + 2768.0 * c.powi(4)
                    + 576.0 * c.powi(3)
                    + 64.0 * c.powi(2),
            ),
            term([2, 14], 13888.0000000000),
            term([2, 12], 85408.0 * c),
            term([2, 10], 220800.0 * c.powi(2) + 13120.0 * c),
            term([2, 8], 308960.0 * c.powi(3) + 55072.0 * c.powi(2)),
            term(
                [2, 6],
                249920.0 * c.powi(4) + 89088.0 * c.powi(3) + 3872.0 * c.powi(2) + 576.0 * c,
            ),
            term(
                [2, 4],
                114528.0 * c.powi(5)
                    + 68032.0 * c.powi(4)
                    + 8848.0 * c.powi(3)
                    + 1312.0 * c.powi(2),
            ),
            term(
                [2, 2],
                26368.0 * c.powi(6)
                    + 23488.0 * c.powi(5)
                    + 6080.0 * c.powi(4)
                    + 1216.0 * c.powi(3)
                    + 128.0 * c.powi(2),
            ),
            term(
                [2, 0],
                2080.0 * c.powi(7)
                    + 2592.0 * c.powi(6)
                    + 1104.0 * c.powi(5)
                    + 320.0 * c.powi(4)
                    + 64.0 * c.powi(3),
            ),
            term([1, 15], 4160.00000000000),
            term([1, 13], 29120.0 * c),
            term([1, 11], 87360.0 * c.powi(2) + 5184.0 * c),
            term([1, 9], 145600.0 * c.powi(3) + 25920.0 * c.powi(2)),
            term(
                [1, 7],
                145600.0 * c.powi(4) + 51840.0 * c.powi(3) + 2208.0 * c.powi(2) + 320.0 * c,
            ),
            term(
                [1, 5],
                87360.0 * c.powi(5) + 51840.0 * c.powi(4) + 6624.0 * c.powi(3) + 960.0 * c.powi(2),
            ),
            term(
                [1, 3],
                29120.0 * c.powi(6)
                    + 25920.0 * c.powi(5)
                    + 6624.0 * c.powi(4)
                    + 1280.0 * c.powi(3)
                    + 128.0 * c.powi(2),
            ),
            term(
                [1, 1],
                4160.0 * c.powi(7)
                    + 5184.0 * c.powi(6)
                    + 2208.0 * c.powi(5)
                    + 640.0 * c.powi(4)
                    + 128.0 * c.powi(3),
            ),
            term([1, 0], -1.00000000000000),
            term([0, 16], 676.000000000000),
            term([0, 14], 5408.0 * c),
            term([0, 12], 18928.0 * c.powi(2) + 1144.0 * c),
            term([0, 10], 37856.0 * c.powi(3) + 6864.0 * c.powi(2)),
            term(
                [0, 8],
                47320.0 * c.powi(4) + 17160.0 * c.powi(3) + 744.0 * c.powi(2) + 104.0 * c,
            ),
            term(
                [0, 6],
                37856.0 * c.powi(5) + 22880.0 * c.powi(4) + 2976.0 * c.powi(3) + 416.0 * c.powi(2),
            ),
            term(
                [0, 4],
                18928.0 * c.powi(6)
                    + 17160.0 * c.powi(5)
                    + 4464.0 * c.powi(4)
                    + 844.0 * c.powi(3)
                    + 88.0 * c.powi(2),
            ),
            term(
                [0, 2],
                5408.0 * c.powi(7)
                    + 6864.0 * c.powi(6)
                    + 2976.0 * c.powi(5)
                    + 856.0 * c.powi(4)
                    + 176.0 * c.powi(3),
            ),
            term(
                [0, 0],
                676.0 * c.powi(8)
                    + 1144.0 * c.powi(7)
                    + 744.0 * c.powi(6)
                    + 324.0 * c.powi(5)
                    + 113.0 * c.powi(4)
                    + 20.0 * c.powi(3)
                    + 4.0 * c.powi(2)
                    + c,
            ),
        ],
        vec![
            term([0, 16], 1.00000000000000),
            term([0, 14], 8.0 * c),
            term([0, 12], 28.0 * c.powi(2) + 4.0 * c),
            term([0, 10], 56.0 * c.powi(3) + 24.0 * c.powi(2)),
            term(
                [0, 8],
                70.0 * c.powi(4) + 60.0 * c.powi(3) + 6.0 * c.powi(2) + 2.0 * c,
            ),
            term(
                [0, 6],
                56.0 * c.powi(5) + 80.0 * c.powi(4) + 24.0 * c.powi(3) + 8.0 * c.powi(2),
            ),
            term(
                [0, 4],
                28.0 * c.powi(6)
                    + 60.0 * c.powi(5)
                    + 36.0 * c.powi(4)
                    + 16.0 * c.powi(3)
                    + 4.0 * c.powi(2),
            ),
            term(
                [0, 2],
                8.0 * c.powi(7)
                    + 24.0 * c.powi(6)
                    + 24.0 * c.powi(5)
                    + 16.0 * c.powi(4)
                    + 8.0 * c.powi(3),
            ),
            term([0, 1], -1.00000000000000),
            term(
                [0, 0],
                c.powi(8)
                    + 4.0 * c.powi(7)
                    + 6.0 * c.powi(6)
                    + 6.0 * c.powi(5)
                    + 5.0 * c.powi(4)
                    + 2.0 * c.powi(3)
                    + c.powi(2)
                    + c,
            ),
        ],
    ])?;

    let result = PolsysSolver::new().solve(&mut poly)?;

    println!("Found {} roots:", result.n_roots());
    let mut all_inside = true;
    for (i, root) in result.affine_roots().enumerate() {
        let norm = root.iter().map(|z| z.norm()).sum::<f64>().sqrt();
        println!("{i:2}: {root:?}");
        if norm >= 1.0 {
            all_inside = false;
        }
    }
    println!("[ROOTS] |z| < 1: {}", if all_inside { "YES" } else { "NO" },);

    Ok(())
}
