// GENERATED by generate_fixed_point.py
// DO NOT EDIT

// SPDX-FileCopyrightText: 2026 Alexandru Fikl <alexfikl@gmail.com>
// SPDX-License-Identifier: MIT

use num::complex::Complex64;

use polsys::{PolsysSolver, Polynomial, term};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let c = Complex64::new(0.0, 0.0);
    let mut poly = Polynomial::<2>::new(vec![
        vec![
            term([4, 0], 1.00000000000000),
            term([3, 1], 4.00000000000000),
            term([2, 2], 8.00000000000000),
            term([2, 0], 4.0 * c),
            term([1, 3], 8.00000000000000),
            term([1, 1], 8.0 * c),
            term([1, 0], -1.00000000000000),
            term([0, 4], 4.00000000000000),
            term([0, 2], 8.0 * c),
            term([0, 0], 4.0 * c.powi(2) + c),
        ],
        vec![
            term([0, 4], 1.00000000000000),
            term([0, 2], 2.0 * c),
            term([0, 1], -1.00000000000000),
            term([0, 0], c.powi(2) + c),
        ],
    ])?;

    let result = PolsysSolver::new().solve(&mut poly)?;

    println!("Found {} roots:", result.n_roots());
    for (i, root) in result.affine_roots().enumerate() {
        println!("{i:2}: {root:?}");
    }

    Ok(())
}
