# SPDX-FileCopyrightText: 2026 Alexandru Fikl <alexfikl@gmail.com>
# SPDX-License-Identifier: MIT

from __future__ import annotations

import logging
import pathlib
from typing import TypeAlias

import rich.logging
import sympy as sp

log = logging.getLogger(pathlib.Path(__file__).stem)
log.setLevel(logging.ERROR)
log.addHandler(rich.logging.RichHandler())

SCRIPT_PATH = pathlib.Path(__file__)
SCRIPT_LONG_HELP = f"""\
Generate a Rust example for polsys-rs that finds fixed points of

    f(z) = (A z)^2 + c

where `A` is a real `(d, d)` matrix, `c` is a complex scalar, `z is a complex
vector, and the square is taken element-wise. The script expands f^k(z) - z =
0 symbolically with sympy and emits a compilable Rust file.

Example:

    > python {SCRIPT_PATH.name} -o examples/fixed_point_example.rs
"""

# {{{ build system


def build_system(
    A: sp.Matrix,
    z: tuple[sp.Symbol, ...],
    *,
    k: int = 1,
) -> tuple[sp.Expr, ...]:
    d = len(z)
    if A.shape != (d, d):
        raise ValueError(f"'A' must be {d}x{d}: {A.shape}")

    c = sp.Symbol("c", complex=True)
    z = sp.Matrix(z)
    ones = sp.Matrix([1] * d)

    def f(vec: sp.Matrix) -> sp.Matrix:
        y = A * vec
        return sp.Matrix([yi**2 for yi in y]) + c * ones

    current = z
    for _ in range(k):
        current = f(current)

    return tuple(sp.expand(eq) for eq in (current - z))


# }}}


# {{{ extract_terms


def extract_terms(
    poly_expr: sp.Expr,
    z: tuple[sp.Symbol, ...],
) -> list[tuple[tuple[int, ...], complex]]:
    d = len(z)
    poly = sp.Poly(poly_expr, *z)

    terms: list[tuple[tuple[int, ...], sp.Expr]] = []
    for monom, coeff in poly.terms():
        assert len(monom) == d

        exponent_tuple = tuple(int(e) for e in monom)
        if isinstance(coeff, sp.Number):
            coeff = coeff.evalf()

        terms.append((exponent_tuple, coeff))

    return terms


# }}}


# {{{ generate_rust

# REUSE-IgnoreStart
RUST_CODE_TEMPLATE = """\
// GENERATED by {program}
// DO NOT EDIT

// SPDX-FileCopyrightText: 2026 Alexandru Fikl <alexfikl@gmail.com>
// SPDX-License-Identifier: MIT

use num::complex::Complex64;

use polsys::{{PolsysSolver, Polynomial, term}};

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let c = Complex64::new(0.0, 0.0);
    let mut poly = Polynomial::<{d}>::new(vec![
        {polynomial}
    ])?;

    let result = PolsysSolver::new().solve(&mut poly)?;

    println!("Found {{}} roots:", result.n_roots());
    for (i, root) in result.affine_roots().enumerate() {{
        println!("{{i:2}}: {{root:?}}");
    }}

    Ok(())
}}
"""
# REUSE-IgnoreEnd

Degree: TypeAlias = tuple[int, ...]
Coefficient: TypeAlias = sp.Expr


def generate_rust(
    terms_per_eq: list[list[tuple[Degree, Coefficient]]],
    d: int,
    *,
    description: str = "",
) -> str:
    equations = []
    for idx, terms in enumerate(terms_per_eq):
        result = []
        for degrees, coeffs in terms:
            s_degrees = ", ".join(str(deg) for deg in degrees)
            s_coeff = str(coeffs)
            result.append(f"term([{s_degrees}], {s_coeff})")

        eq = ", ".join(result)
        equations.append(f"vec![{eq}]")

    return RUST_CODE_TEMPLATE.format(
        program=SCRIPT_PATH.name,
        d=d,
        polynomial=",\n        ".join(equations),
    )


# }}}


def main(
    filename: pathlib.Path,
    *,
    k: int = 1,
    overwrite: bool = False,
) -> int:
    if not overwrite and filename.exists():
        log.error("File already exists (use --force to overwrite): '%s'", filename)
        return 1

    mat: list[list[float]] = [
        [1, 1],
        [0, 1],
    ]

    d = len(mat)
    if d < 1:
        raise ValueError(f"dimension 'd' must be >= 1: {d}")

    A = sp.Matrix([[sp.Rational(x) for x in row] for row in mat])
    z = sp.symbols(f"z0:{d}", complex=True)

    system = build_system(A, z, k=k)
    terms_per_eq = [extract_terms(eq, z) for eq in system]
    rust_source = generate_rust(terms_per_eq, d)

    with open(filename, "w") as f:
        f.write(rust_source)

    log.info("Written generated code: '%s'.", filename)
    import subprocess

    try:
        subprocess.run(
            ["cargo", "fmt", "--", str(filename)],
            capture_output=True,
            check=True,
        )
        log.info("Formatted generated code (`cargo fmt`): '%s'", filename)
    except subprocess.SubprocessError as exc:
        log.warning("[cargo fmt] %s", exc.stderr.decode())
        return 1

    return 0


if __name__ == "__main__":
    import argparse

    class HelpFormatter(
        argparse.ArgumentDefaultsHelpFormatter,
        argparse.RawDescriptionHelpFormatter,
    ):
        pass

    parser = argparse.ArgumentParser(
        formatter_class=HelpFormatter,
        description=SCRIPT_LONG_HELP,
    )
    parser.add_argument(
        "-o",
        "--outfile",
        type=pathlib.Path,
        default="fixed_point_example.rs",
        help="name of the output file",
    )
    parser.add_argument(
        "-p",
        "--period",
        type=int,
        default=1,
        help="period to generate the polynomial system from",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="force overwrite of existing files",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Only show error messages",
    )
    args = parser.parse_args()

    if not args.quiet:
        log.setLevel(logging.INFO)

    raise SystemExit(main(args.outfile, k=args.period, overwrite=args.force))
