name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '30 12 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    name: Licensing (REUSE)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v4

  typos:
    name: Spelling (typos)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: crate-ci/typos@master

  fortitude:
    name: Linting (fortitude)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        cargo install fortitude
        make fortitude

  clippy:
    name: Linting (clippy)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        make clippy

  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Testing (${ runner.os })
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: |
        make test

# vim: set ts=2 sw=2 et:
